#!/usr/bin/env python3
"""Render the public GitHub profile README from the canonical profile data."""

from __future__ import annotations

import argparse
import html
import sys
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from profile_data import load_profile


ROOT = SCRIPT_DIR.parent
README_PATH = ROOT / "README.md"
PROFILE_REPOSITORY = "Yorayriniwnl"
SELECTED_PROJECT_IDS = ("portfolio", "helios", "zenith", "vision", "talks")
PROJECT_VISUALS = {
    "portfolio": "project-portfolio.svg",
    "helios": "project-helios.svg",
    "zenith": "project-zenith.svg",
    "vision": "project-vision.svg",
    "talks": "project-talks.svg",
}


def raw_asset_url(handle: str, filename: str) -> str:
    return f"https://raw.githubusercontent.com/{handle}/{PROFILE_REPOSITORY}/output/{filename}"


def image(filename: str, alt: str, handle: str, width: str = "100%") -> str:
    return (
        f'<img src="{raw_asset_url(handle, filename)}" width="{width}" '
        f'alt="{html.escape(alt, quote=True)}"/>'
    )


def linked_image(href: str, filename: str, alt: str, handle: str, width: str = "100%") -> list[str]:
    return [f'<a href="{href}">', image(filename, alt, handle, width), "</a>"]


def project_block(project: dict, handle: str) -> list[str]:
    code = f'SYS-{project["order"]:02d}'
    target = project.get("live") or project["repo"]
    status = f'{project["status"]} · {project["period"]}'
    stack = " · ".join(project["stack"])
    links = []
    if project.get("live"):
        links.append(f'[Live system ↗]({project["live"]})')
    links.append(f'[Source ↗]({project["repo"]})')

    lines = [
        f'### `{code}` · {project["name"]}',
        "",
        f'**{status}**',
        "",
        *linked_image(
            target,
            PROJECT_VISUALS[project["id"]],
            f'{project["name"]}: {project["codename"].lower()}',
            handle,
        ),
        "",
        project["summary"],
        "",
        "Proof:",
        "",
    ]
    lines.extend(f'- {proof}' for proof in project["proof"])
    lines.extend(["", f'**Stack:** {stack}', "", " · ".join(links), ""])
    return lines


def render_readme(profile: dict | None = None) -> str:
    profile = profile or load_profile()
    identity = profile["identity"]
    contact = profile["contact"]
    availability = profile["availability"]
    handle = identity["handle"]
    projects = {project["id"]: project for project in profile["projects"]}
    proof = {item["id"]: item for item in profile["proof"]}
    experience = profile["experience"][0]
    education = profile["education"][0]
    skills = profile["skills"]
    resume_url = (
        f'https://github.com/{handle}/{PROFILE_REPOSITORY}/blob/main/'
        "output/pdf/Ayush_Roy_Resume_Public.pdf"
    )

    lines = [
        "<!-- Generated by scripts/generate_readme.py from data/profile.json. -->",
        "",
        '<div align="center">',
        "",
        *linked_image(
            contact["portfolio"],
            "hero.svg",
            f'{identity["name"]}, {identity["role"].lower()} and {identity["specialty"].lower()}',
            handle,
        ),
        "",
        f'<h1>{html.escape(identity["name"])}</h1>',
        f'<p><strong>{html.escape(identity["role"])} · {html.escape(identity["specialty"])}</strong></p>',
        f'<p>{html.escape(identity["positioning"])}</p>',
        (
            f'<p><strong>{html.escape(availability["status"])} · '
            f'B.Tech {availability["graduating"]} · {html.escape(identity["location"])}</strong></p>'
        ),
        "",
        '<p>',
        f'<a href="{contact["portfolio"]}">{image("nav-portfolio.svg", "Open Ayush Roy portfolio", handle, "350")}</a>',
        f'<a href="{contact["github"]}?tab=repositories">{image("nav-projects.svg", "Explore Ayush Roy projects", handle, "350")}</a>',
        '<br/>',
        f'<a href="{resume_url}">{image("nav-resume.svg", "View Ayush Roy public resume", handle, "350")}</a>',
        f'<a href="{contact["linkedin"]}">{image("nav-linkedin.svg", "Open Ayush Roy LinkedIn profile", handle, "350")}</a>',
        "</p>",
        "",
        image(
            "signal-strip.svg",
            "Product engineering, realtime systems, computer vision, 3D interfaces, and applied AI",
            handle,
        ),
        "",
        '<p>',
        f'<code>{int(proof["apps"]["value"]):02d} · {proof["apps"]["label"]}</code>',
        f'<code>{proof["tests"]["value"]} · TESTS / 5 SUITES</code>',
        f'<code>{proof["accuracy"]["value"]} · HELD-OUT ACCURACY</code>',
        f'<code>{int(proof["prototypes"]["value"]):02d} · {proof["prototypes"]["label"]}</code>',
        "</p>",
        "",
        "</div>",
        "",
        image("section-projects.svg", "Section 01: selected systems, proof before promise", handle),
        "",
        "## Selected systems",
        "",
        (
            "Five end-to-end builds across product engineering, realtime infrastructure, "
            "applied machine learning, and 3D decision tools. Every metric below is backed "
            "by the public project or verified résumé data."
        ),
        "",
    ]

    for project_id in SELECTED_PROJECT_IDS:
        lines.extend(project_block(projects[project_id], handle))

    feelings = projects["feelings"]
    lines.extend(
        [
            "<details>",
            f'<summary><strong>LAB-01 // {feelings["name"]} — {feelings["codename"].lower()}</strong></summary>',
            "",
            feelings["summary"],
            "",
            f'**Stack:** {" · ".join(feelings["stack"])}',
            "",
            f'[Live experiment ↗]({feelings["live"]}) · [Source ↗]({feelings["repo"]})',
            "",
            "</details>",
            "",
            "## Field notes",
            "",
            f'**{experience["role"]} · {experience["organization"]}** — {experience["period"]}',
            "",
            experience["summary"],
            "",
            f'**{education["degree"]} · {education["institution"]}** — expected {availability["graduating"]}',
            "",
            (
                "Grounded in data structures, operating systems, databases, computer networks, "
                "and object-oriented programming."
            ),
            "",
            f'[View privacy-safe public résumé ↗]({resume_url})',
            "",
            image("section-arsenal.svg", "Section 02: technical range", handle),
            "",
            "## Technical range",
            "",
            image("arsenal.svg", "Ayush Roy technical range across product, backend, machine learning, and platform engineering", handle),
            "",
            f'**Product:** {" · ".join(skills["product"])}',
            "",
            f'**Backend:** {" · ".join(skills["backend"])}',
            "",
            f'**Applied ML:** {" · ".join(skills["ml"])}',
            "",
            f'**Platform:** {" · ".join(skills["platform"])}',
            "",
            f'**Currently expanding:** {" · ".join(skills["expanding"])}',
            "",
            image("section-record.svg", "Section 03: public GitHub record", handle),
            "",
            "## Public record",
            "",
            *linked_image(
                contact["github"],
                "stats.svg",
                "Ayush Roy GitHub repositories, languages, and current system status",
                handle,
            ),
            "",
            "The live card is generated from public GitHub data; its fallback contains only verified profile facts.",
            "",
            "## Operator mode",
            "",
            "<details>",
            '<summary><strong>◈ INITIATE OPERATOR MODE // STEAM-INSPIRED PERSONAL LAYER</strong></summary>',
            "",
            image("operator-gateway.svg", "Operator mode access gateway", handle),
            "",
            image("achievement-rack.svg", "Proof-of-work achievement rack", handle),
            "",
            "<details>",
            '<summary><strong>01 // TRACE THE ENGINEERING DNA</strong></summary>',
            "",
            image("protocol-engineer.svg", "Engineering protocol from constraints through feedback", handle),
            "",
            "</details>",
            "",
            "<details>",
            '<summary><strong>02 // FORGE THE PRODUCT DOCTRINE</strong></summary>',
            "",
            image("protocol-product.svg", "Product doctrine and learning loop", handle),
            "",
            "</details>",
            "",
            "<details>",
            '<summary><strong>03 // OPEN THE HUMAN ARCHIVE</strong></summary>',
            "",
            *linked_image(
                contact["steam"],
                "protocol-human.svg",
                "Steam-inspired human signal and long-game philosophy",
                handle,
            ),
            "",
            "</details>",
            "",
            "</details>",
            "",
            "## Open channel",
            "",
            (
                "I’m open to software engineering internships, ambitious product work, and "
                "collaborations where interface craft meets real systems."
            ),
            "",
            f'[Email](mailto:{contact["email"]}) · [LinkedIn]({contact["linkedin"]}) · '
            f'[Portfolio]({contact["portfolio"]}) · [GitHub]({contact["github"]}) · '
            f'[Devpost]({contact["devpost"]}) · [Steam]({contact["steam"]})',
            "",
            '<div align="center">',
            "",
            *linked_image(
                f'mailto:{contact["email"]}?subject=Next%20Transmission',
                "finale.svg",
                "Grind. Build. Repeat. Open a collaboration channel with Ayush Roy",
                handle,
            ),
            "",
            "</div>",
            "",
        ]
    )

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if README.md is out of date")
    args = parser.parse_args()
    rendered = render_readme()

    if args.check:
        current = README_PATH.read_text(encoding="utf-8") if README_PATH.is_file() else ""
        if current != rendered:
            print("README.md is out of date; run scripts/generate_readme.py", file=sys.stderr)
            return 1
        print("README.md matches canonical profile data")
        return 0

    README_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {README_PATH} ({len(rendered):,} characters)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
