#!/usr/bin/env python3
"""Render the public GitHub profile from canonical data and owned visual assets."""
from __future__ import annotations

import argparse
import html
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))
from profile_data import load_profile
from redline import ORDER

ROOT = SCRIPT_DIR.parent
README_PATH = ROOT / "README.md"
PROFILE_REPOSITORY = "Yorayriniwnl"
SELECTED_PROJECT_IDS = ORDER
PROJECT_VISUALS = {p: f"project-{p}.svg" for p in ORDER}
PROJECT_VISUALS["portfolio"] = "project-portfolio-v2.svg"
MOTION_ASSETS = (
    "systems-reel-v9.gif",
    "systems-reel-mobile-v9.gif",
    "systems-reel-v9-still.png",
    "systems-reel-mobile-v9-still.png",
)
ASSET_REVISIONS = {
    "hero.svg": "command-v2",
    "project-portfolio-v2.svg": "raster-v8",
    "project-portfolio-mobile-v2.svg": "raster-v8",
    "project-helios.svg": "raster-v15",
    "project-zenith.svg": "raster-v14",
    "project-vision.svg": "raster-v16",
    "project-talks.svg": "raster-v14",
    "project-token-usage.svg": "raster-v15",
    **{name: "motion-v9" for name in MOTION_ASSETS},
}


def raw_asset_url(handle, filename):
    revision = ASSET_REVISIONS.get(filename, "spectrum-v1")
    return f"https://raw.githubusercontent.com/{handle}/{PROFILE_REPOSITORY}/output/{filename}?rev={revision}"


def profile_views_url(handle):
    return f"https://komarev.com/ghpvc/?username={handle}&amp;label=TOTAL+PROFILE+VIEWS&amp;color=ff1f2d&amp;style=for-the-badge&amp;abbreviated=false"


def image(filename, alt, handle, width="100%"):
    tag = f'<img src="{raw_asset_url(handle, filename)}" width="{width}" alt="{html.escape(alt, quote=True)}"/>'
    if filename == "project-portfolio-v2.svg":
        mobile = "project-portfolio-mobile-v2.svg"
        return f'<picture><source media="(max-width: 600px)" srcset="{raw_asset_url(handle, mobile)}"/>{tag}</picture>'
    return tag


def linked_image(href, filename, alt, handle, width="100%"):
    return f'<a href="{html.escape(href, quote=True)}">{image(filename, alt, handle, width)}</a>'


def markdown_link(label, href):
    return f"[{label}]({href})"


def systems_reel(handle):
    variants = (
        ("(max-width: 600px) and (prefers-reduced-motion: reduce)", "systems-reel-mobile-v9-still.png"),
        ("(prefers-reduced-motion: reduce)", "systems-reel-v9-still.png"),
        ("(max-width: 600px)", "systems-reel-mobile-v9.gif"),
    )
    sources = [f'<source media="{media}" srcset="{raw_asset_url(handle, asset)}"/>' for media, asset in variants]
    return ["<picture>", *sources,
            image("systems-reel-v9.gif", "Six project worlds in motion: product design, energy telemetry, solar planning, image forensics, realtime communication, and local AI usage. Illustrative artwork, not live telemetry.", handle),
            "</picture>"]


def project_block(project, handle, index):
    pid = project["id"]
    target = project.get("live") or project["repo"]
    proof = "\n".join(f"- {fact}" for fact in project["proof"])
    links = [markdown_link("Source", project["repo"])]
    if project.get("live"):
        links.insert(0, markdown_link("Live demo", project["live"]))
    return [
        f'<a id="project-{pid}"></a>',
        f'### {index:02d} / {project["name"]}',
        f'`{project["status"]}` · {project["period"]}',
        "",
        project["summary"],
        "",
        linked_image(target, PROJECT_VISUALS[pid], f'Cinematic artwork for {project["name"]}.', handle),
        "",
        f'**Stack:** {" · ".join(project["stack"])}',
        f'**Explore:** {" · ".join(links)}',
        "",
        "<details>",
        f'<summary>Build notes and proof ({len(project["proof"])} items)</summary>',
        "",
        proof,
        "",
        "</details>",
        "",
    ]


def render_readme(profile=None):
    p = profile or load_profile()
    contact = p["contact"]
    identity = p["identity"]
    handle = identity["handle"]
    resume = f"https://github.com/{handle}/{PROFILE_REPOSITORY}/blob/main/output/pdf/Ayush_Roy_Resume_Public.pdf"
    projects = {project["id"]: project for project in p["projects"]}
    project_links = [markdown_link(f"{index:02d} {projects[pid]['name']}", f"#user-content-project-{pid}")
                     for index, pid in enumerate(ORDER, start=1)]

    lines = [
        "<!-- Generated by scripts/generate_readme.py from data/profile.json. -->",
        "",
        '<div align="center">',
        linked_image(contact["portfolio"], "hero.svg", "Cinematic crimson portrait artwork with a six-world command interface.", handle),
        "</div>",
        "",
        f"# {identity['name']}",
        f"**{identity['role']}** · **{identity['specialty']}**",
        "",
        identity["positioning"],
        "",
        f"**{p['availability']['status']}** · {identity['location']} · {identity['timezone']}",
        "",
        " · ".join((markdown_link("Portfolio", contact["portfolio"]), markdown_link("Résumé", resume),
                    markdown_link("LinkedIn", contact["linkedin"]), markdown_link("GitHub", contact["github"]),
                    markdown_link("Email", f'mailto:{contact["email"]}'))),
        "",
        "## Six worlds / one builder",
        "",
        "Each build gets its own signal color, product language, and operating model. This reel is an illustrative motion study.",
        "",
        '<div align="center">',
        *systems_reel(handle),
        "</div>",
        "",
        "## Selected systems",
        "",
        " · ".join(project_links),
        "",
    ]
    for index, pid in enumerate(ORDER, start=1):
        lines.extend(project_block(projects[pid], handle, index))

    experience = p["experience"][0]
    education = p["education"][0]
    email_link = markdown_link(contact["email"], f"mailto:{contact['email']}")
    lines.extend([
        "## Field notes",
        "",
        f'**{experience["role"]} · {experience["organization"]}** — {experience["period"]}, {experience["location"]}. {experience["summary"]}',
        "",
        f'**{education["degree"]} · {education["institution"]}** — {education["period"]}, {education["location"]}.',
        "",
        f'**Focus:** {" · ".join(education["coursework"])}',
        "",
        f'**Current range:** {" · ".join(p["skills"]["product"])} · {" · ".join(p["skills"]["backend"])} · {" · ".join(p["skills"]["ml"])} · {" · ".join(p["skills"]["platform"])}',
        "",
        "<details>",
        "<summary>Credentials and off-screen chapters</summary>",
        "",
        "**Credentials**",
        *[f'- {item["name"]} — {item["issuer"]}, {item["date"]}' for item in p["certifications"]],
        "",
        "**Other chapters**",
        *[f"- {item}" for item in p["achievements"]],
        f'- Off the clock: {markdown_link("Steam profile", contact["steam"])}',
        "",
        "</details>",
        "",
        "## Public signal",
        "",
        '<p align="center">',
        f'<img src="{profile_views_url(handle)}" width="350" alt="Total profile views, as counted by Komarev"/>',
        "</p>",
        "",
        linked_image(contact["github"], "stats.svg", "Timestamped public GitHub snapshot: repositories, stars, followers, and languages.", handle),
        "",
        linked_image(contact["github"], "contribution-stream.svg", "GitHub contribution activity for the labeled 365-day date range.", handle),
        "",
        "## Open channel",
        "",
        f'For roles, product builds, and thoughtful collaborations: {email_link} · {markdown_link("LinkedIn", contact["linkedin"])} · {markdown_link("Devpost", contact["devpost"])}.',
        "",
    ])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_readme()
    if args.check:
        if not README_PATH.is_file() or README_PATH.read_text(encoding="utf-8") != rendered:
            print("README.md is out of date; run scripts/generate_readme.py", file=sys.stderr)
            return 1
        print("README.md matches canonical profile data")
        return 0
    README_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {README_PATH} ({len(rendered):,} characters)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
