name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

concurrency:
  group: profile-output
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout output
        uses: actions/checkout@v4
        with:
          ref: output
          path: output

      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: yorayriniwnl
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: output
          commit_message: "chore: update snake animation"
          branch: output
